controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Homepage
home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET